name: Build mdBook into docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'mds/**'
      - 'book.toml'
      - '.github/workflows/build-book.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mdBook
        run: cargo install mdbook

      - name: Build the book
        run: mdbook build

      - name: Commit and push built docs
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "Auto-update book [skip ci]" || echo "No changes to commit"
          git push
